feat: add faqs page
cesium/ares pull request #17
Opened 2024-02-14 21:20 UTC by danielsp45

2024-02-16 19:22 UTC, MarioRodrigues10 requested changes

2024-02-16 19:22 UTC, MarioRodrigues10 commented on src/components/intro.astro
> +    </p>
Use uppercase

2024-02-16 19:22 UTC, MarioRodrigues10 commented on src/components/faqs.jsx
> +                            </svg>
Use an HeroIcon here instead or remove the library.

2024-02-16 19:22 UTC, MarioRodrigues10 commented on src/components/faqs.jsx
> +                            </svg>
Use an HeroIcon here instead or remove the library.

2024-02-16 22:12 UTC, joaodiaslobo requested changes
In order to maintain coherent code standards on all of our repos, it would be better if the FAQ questions were placed on a JSON file instead of being hardcoded.
Something like what is done on [seium.org](https://github.com/cesium/seium.org/blob/main/data/faqs.json)

2024-02-16 22:18 UTC, MarioRodrigues10 requested changes
It would be nice to have a smooth animation when opening a faq question.
You can follow [this](https://github.com/cesium/seium.org/blob/main/layout/FAQs/components/Question/index.tsx) example

2024-02-17 01:07 UTC, joaodiaslobo approved these changes
🪲💚

2024-02-17 09:35 UTC, merged